version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=universidad
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pablo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pablo"
    ports:
      - "90:80"
    depends_on:
      - postgres